[tool.poetry]
name = "judo"
version = "0.1.0"
description = ""
authors = ["Anthony Miyaguchi <acmiyaguchi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
opencv-python = "^4.8.0.76"
matplotlib = "^3.7.2"
pandas = "^2.0.3"
pytesseract = "^0.3.10"
scipy = "^1.11.2"

[tool.poetry.dev-dependencies]
jupyterlab = "^4.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
